import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/NavBar'
import ParallaxEffect from '../components/ParallaxEffect'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Koustav Mondal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Navigation Bar*/}
      <NavBar/>
      
      {/*Main Screen Parallax Effect*/}
      {/*<ParallaxEffect/>*/}
      

    </div>
  )
}
